"""empty message

Revision ID: 03c76b5ce6af
Revises: 95f0704c913e
Create Date: 2025-03-05 15:31:17.845736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c76b5ce6af'
down_revision: Union[str, None] = '95f0704c913e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
