"""empty message

Revision ID: 2c8fc78077aa
Revises: 03c76b5ce6af
Create Date: 2025-03-05 16:06:07.846994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8fc78077aa'
down_revision: Union[str, None] = '03c76b5ce6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transactions', 'name',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
