"""create_table_for_users

Revision ID: 7f62c15a3a9d
Revises: e62593df46f8
Create Date: 2025-04-16 03:55:14.064522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f62c15a3a9d"
down_revision: Union[str, None] = "e62593df46f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.add_column("categories", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["user_id"])
    op.add_column("transactions", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "user_id")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
