"""create_tables_for_transactions_and_categories

Revision ID: e62593df46f8
Revises:
Create Date: 2025-04-16 03:53:51.563563

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e62593df46f8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("category_name", sa.String(length=50), nullable=False),
        sa.Column("category_description", sa.String(length=200), nullable=False),
        sa.Column(
            "category_type",
            sa.Enum("income", "expenses", name="categorytype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("income", "expenses", name="transactiontype"),
            nullable=False,
        ),
        sa.Column(
            "transaction_value", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("transaction_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_description", sa.String(length=200), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("categories")
    # ### end Alembic commands ###
