"""Add_finite_statue_machine_field_to_the_report's_table

Revision ID: f84f4ef488b4
Revises: 17033d717c43
Create Date: 2025-04-30 04:53:58.151108

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f84f4ef488b4"
down_revision: Union[str, None] = "17033d717c43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "status",
            sa.Enum(
                "CREATED", "GENERATED", "FAILED", name="reportstatus"
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "reports",
        "month_income",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "reports",
        "month_expenses",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "reports",
        "balance",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reports",
        "balance",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "reports",
        "month_expenses",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "reports",
        "month_income",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.drop_column("reports", "status")
    # ### end Alembic commands ###
